[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.36.2",
    "flask-login>=0.6.3",
    "flask>=3.1.0",
    "qrcode>=8.0",
    "twilio>=9.4.3",
    "werkzeug>=3.1.3",
]
